name = "pickles"
description = "A modern, simple, clean blog theme for Zola."
license = "MIT OR Apache-2.0"
homepage = "https://github.com/lukehsiao/zola-pickles"
# The minimum version of Zola required
min_version = "0.13.0"
# An optional live demo URL
demo = ""

# Any variable there can be overriden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

# The theme author info: you!
[author]
name = "Luke Hsiao"
homepage = "https://luke.hsiao.dev"

# If this is porting a theme from another static site engine, provide
# the info of the original author here
[original]
author =  "Misumi Takuma"
homepage = "https://mismith.me/"
repo = "https://github.com/mismith0227/hugo_theme_pickles"
